const Players = game:GetService("Players")
const RunService = game:GetService("RunService")
const UserInputService = game:GetService("UserInputService")

const player = Players.LocalPlayer
const mouse = player:GetMouse()
const playerGui = Players.LocalPlayer:WaitForChild("PlayerGui")

const connections: { RBXScriptConnection } = {}

const DriveModule = {}

function DriveModule.new()
	local gui = playerGui:WaitForChild("A-Chassis Interface")

	--[[START]]
	gui:WaitForChild("Car")
	gui:WaitForChild("IsOn")
	gui:WaitForChild("ControlsOpen")
	gui:WaitForChild("Values")

	--[[Dependencies]]

	local car = gui.Car.Value
	local module = car:WaitForChild("A-Chassis Tune") :: ModuleScript
	if not module then
		return
	end
	const _Tune = require(module)

	--[[Output Scaling Factor]]

	local hpScaling = _Tune.WeightScaling * 10
	local FBrakeForce = _Tune.FBrakeForce
	local RBrakeForce = _Tune.RBrakeForce
	local PBrakeForce = _Tune.PBrakeForce
	if not workspace:PGSIsEnabled() then
		hpScaling = _Tune.LegacyScaling * 10
		FBrakeForce = _Tune.FLgcyBForce
		RBrakeForce = _Tune.RLgcyBForce
		PBrakeForce = _Tune.LgcyPBForce
	end

	--[[Status Vars]]

	local _IsOn = _Tune.AutoStart
	if _Tune.AutoStart then
		gui.IsOn.Value = true
	end

	local _GSteerT = 0
	local _GSteerC = 0
	local _GThrot = 0
	local _GBrake = 0

	local _ClutchOn = true
	local _ClPressing = false
	local _RPM = 0
	local _HP = 0
	local _OutTorque = 0
	local _CGear = 0
	local _PGear = _CGear
	local _spLimit = 0

	local _TMode = _Tune.TransModes[1]

	local _MSteer = false
	local _SteerL = false
	local _SteerR = false
	local _PBrake = false
	local _TCS = _Tune.TCSEnabled
	local _TCSActive = false
	local _ABS = _Tune.ABSEnabled
	local _ABSActive = false

	local FlipWait = tick()
	local FlipDB = false

	local _InControls = false

	--[[Controls]]

	local _CTRL = _Tune.Controls
	local Controls = Instance.new("Folder")
	Controls.Parent = gui
	Controls.Name = "Controls"

	for i, v in pairs(_CTRL) do
		local strVal = Instance.new("StringValue")
		strVal.Parent = Controls
		strVal.Name = i
		strVal.Value = v.Name
		connections[#connections + 1] = strVal.Changed:connect(function()
			if i == "MouseThrottle" or i == "MouseBrake" then
				if strVal.Value == "MouseButton1" or strVal.Value == "MouseButton2" then
					_CTRL[i] = Enum.UserInputType[strVal.Value]
				else
					_CTRL[i] = Enum.KeyCode[strVal.Value]
				end
			else
				_CTRL[i] = Enum.KeyCode[strVal.Value]
			end
		end)
	end

	--Deadzone Adjust
	local _PPH = _Tune.Peripherals
	for i, v in pairs(_PPH) do
		local intVal = Instance.new("IntValue")
		intVal.Parent = Controls
		intVal.Name = i
		intVal.Value = v
		connections[#connections + 1] = intVal.Changed:connect(function()
			intVal.Value = math.min(100, math.max(0, intVal.Value))
			_PPH[i] = intVal.Value
		end)
	end

	--Input Handler
	local function DealWithInput(input)
		if (UserInputService:GetFocusedTextBox() == nil) and not _InControls then --Ignore when UI Focus
			--Shift Down [Manual Transmission]
			if
				_IsOn
				and (input.KeyCode == _CTRL["ContlrShiftDown"] or (_MSteer and input.KeyCode == _CTRL["MouseShiftDown"]) or ((not _MSteer) and input.KeyCode == _CTRL["ShiftDown"]))
				and (_TMode == "Semi" or (_TMode == "Manual" and not _ClutchOn))
				and input.UserInputState == Enum.UserInputState.Begin
			then
				if _CGear == 0 and not _ClPressing then
					_ClutchOn = true
				end
				_CGear = math.max(_CGear - 1, -1)

			--Shift Up [Manual Transmission]
			elseif
				_IsOn
				and (input.KeyCode == _CTRL["ContlrShiftUp"] or (_MSteer and input.KeyCode == _CTRL["MouseShiftUp"]) or ((not _MSteer) and input.KeyCode == _CTRL["ShiftUp"]))
				and (_TMode == "Semi" or (_TMode == "Manual" and not _ClutchOn))
				and input.UserInputState == Enum.UserInputState.Begin
			then
				if _CGear == 0 and not _ClPressing then
					_ClutchOn = true
				end
				_CGear = math.min(_CGear + 1, #_Tune.Ratios - 2)

			--Toggle Clutch
			elseif
				_IsOn
				and (input.KeyCode == _CTRL["ContlrClutch"] or (_MSteer and input.KeyCode == _CTRL["MouseClutch"]) or ((not _MSteer) and input.KeyCode == _CTRL["Clutch"]))
				and _TMode == "Manual"
			then
				if input.UserInputState == Enum.UserInputState.Begin then
					_ClutchOn = false
					_ClPressing = true
				elseif input.UserInputState == Enum.UserInputState.End then
					_ClutchOn = true
					_ClPressing = false
				end

			--Toggle PBrake
			elseif
				_IsOn and input.KeyCode == _CTRL["ContlrPBrake"]
				or (_MSteer and input.KeyCode == _CTRL["MousePBrake"])
				or ((not _MSteer) and input.KeyCode == _CTRL["PBrake"])
			then
				if input.UserInputState == Enum.UserInputState.Begin then
					_PBrake = not _PBrake
				elseif input.UserInputState == Enum.UserInputState.End then
					if car.DriveSeat.Velocity.Magnitude > 5 then
						_PBrake = false
					end
				end

			--Toggle Transmission Mode
			elseif
				(input.KeyCode == _CTRL["ContlrToggleTMode"] or input.KeyCode == _CTRL["ToggleTransMode"])
				and input.UserInputState == Enum.UserInputState.Begin
			then
				local n = 1
				for i, v in pairs(_Tune.TransModes) do
					if v == _TMode then
						n = i
						break
					end
				end
				n = n + 1
				if n > #_Tune.TransModes then
					n = 1
				end
				_TMode = _Tune.TransModes[n]

			--Throttle
			elseif
				_IsOn
					and ((not _MSteer) and (input.KeyCode == _CTRL["Throttle"] or input.KeyCode == _CTRL["Throttle2"]))
				or (
					(
						(
							(
								_CTRL["MouseThrottle"] == Enum.UserInputType.MouseButton1
								or _CTRL["MouseThrottle"] == Enum.UserInputType.MouseButton2
							) and input.UserInputType == _CTRL["MouseThrottle"]
						) or input.KeyCode == _CTRL["MouseThrottle"]
					) and _MSteer
				)
			then
				if input.UserInputState == Enum.UserInputState.Begin then
					_GThrot = 1
				else
					_GThrot = _Tune.IdleThrottle / 100
				end

			--Brake
			elseif
				((not _MSteer) and (input.KeyCode == _CTRL["Brake"] or input.KeyCode == _CTRL["Brake2"]))
				or (
					(
						(
							(
								_CTRL["MouseBrake"] == Enum.UserInputType.MouseButton1
								or _CTRL["MouseBrake"] == Enum.UserInputType.MouseButton2
							) and input.UserInputType == _CTRL["MouseBrake"]
						) or input.KeyCode == _CTRL["MouseBrake"]
					) and _MSteer
				)
			then
				if input.UserInputState == Enum.UserInputState.Begin then
					_GBrake = 1
				else
					_GBrake = 0
				end

			--Steer Left
			elseif (not _MSteer) and (input.KeyCode == _CTRL["SteerLeft"] or input.KeyCode == _CTRL["SteerLeft2"]) then
				if input.UserInputState == Enum.UserInputState.Begin then
					_GSteerT = -1
					_SteerL = true
				else
					if _SteerR then
						_GSteerT = 1
					else
						_GSteerT = 0
					end
					_SteerL = false
				end

			--Steer Right
			elseif not _MSteer and (input.KeyCode == _CTRL["SteerRight"] or input.KeyCode == _CTRL["SteerRight2"]) then
				if input.UserInputState == Enum.UserInputState.Begin then
					_GSteerT = 1
					_SteerR = true
				else
					if _SteerL then
						_GSteerT = -1
					else
						_GSteerT = 0
					end
					_SteerR = false
				end

			--Toggle Mouse Controls
			elseif input.KeyCode == _CTRL["ToggleMouseDrive"] then
				if input.UserInputState == Enum.UserInputState.End then
					_MSteer = not _MSteer
					_GThrot = _Tune.IdleThrottle / 100
					_GBrake = 0
					_GSteerT = 0
					_ClutchOn = true
				end

			--Toggle TCS
			elseif
				_Tune.TCSEnabled and _IsOn and input.KeyCode == _CTRL["ToggleTCS"]
				or input.KeyCode == _CTRL["ContlrToggleTCS"]
			then
				if input.UserInputState == Enum.UserInputState.End then
					_TCS = not _TCS
				end

			--Toggle ABS
			elseif
				_Tune.ABSEnabled and _IsOn and input.KeyCode == _CTRL["ToggleABS"]
				or input.KeyCode == _CTRL["ContlrToggleABS"]
			then
				if input.UserInputState == Enum.UserInputState.End then
					_ABS = not _ABS
				end
			end

			--Variable Controls
			if input.UserInputType.Name:find("Gamepad") then
				--Gamepad Steering
				if input.KeyCode == _CTRL["ContlrSteer"] then
					if input.Position.X >= 0 then
						local cDZone = math.min(0.99, _Tune.Peripherals.ControlRDZone / 100)
						if math.abs(input.Position.X) > cDZone then
							_GSteerT = (input.Position.X - cDZone) / (1 - cDZone)
						else
							_GSteerT = 0
						end
					else
						local cDZone = math.min(0.99, _Tune.Peripherals.ControlLDZone / 100)
						if math.abs(input.Position.X) > cDZone then
							_GSteerT = (input.Position.X + cDZone) / (1 - cDZone)
						else
							_GSteerT = 0
						end
					end

				--Gamepad Throttle
				elseif _IsOn and input.KeyCode == _CTRL["ContlrThrottle"] then
					_GThrot = math.max(_Tune.IdleThrottle / 100, input.Position.Z)

				--Gamepad Brake
				elseif input.KeyCode == _CTRL["ContlrBrake"] then
					_GBrake = input.Position.Z
				end
			end
		else
			_GThrot = _Tune.IdleThrottle / 100
			_GSteerT = 0
			_GBrake = 0
			if _CGear ~= 0 then
				_ClutchOn = true
			end
		end
	end

	-- Mobile support
	local Buttons = gui:WaitForChild("Buttons")
	local Left = Buttons:WaitForChild("Left")
	local Right = Buttons:WaitForChild("Right")
	local Brake = Buttons:WaitForChild("Brake")
	local Gas = Buttons:WaitForChild("Gas")
	local Handbrake = Buttons:WaitForChild("Handbrake")

	if UserInputService.TouchEnabled then
		Buttons.Visible = true
		gui:WaitForChild("AC6_Stock_Gauges").Visible = false
	end

	local function LeftTurn(Touch)
		if Touch.UserInputState == Enum.UserInputState.Begin then
			_GSteerT = -1
			_SteerL = true
		else
			if _SteerR then
				_GSteerT = 1
			else
				_GSteerT = 0
			end
			_SteerL = false
		end
	end

	local function RightTurn(Touch)
		if Touch.UserInputState == Enum.UserInputState.Begin then
			_GSteerT = 1
			_SteerR = true
		else
			if _SteerL then
				_GSteerT = -1
			else
				_GSteerT = 0
			end
			_SteerR = false
		end
	end

	local function TouchThrottle(input)
		if input.UserInputState == Enum.UserInputState.Begin and _IsOn then
			_GThrot = 1
		else
			_GThrot = _Tune.IdleThrottle / 100
		end
	end

	local function TouchBrake(input)
		if input.UserInputState == Enum.UserInputState.Begin then
			_GBrake = 1
		else
			_GBrake = 0
		end
	end

	local function TouchHandbrake(input)
		if input.UserInputState == Enum.UserInputState.Begin then
			_PBrake = not _PBrake
		elseif input.UserInputState == Enum.UserInputState.End then
			if car.DriveSeat.Velocity.Magnitude > 5 then
				_PBrake = false
			end
		end
	end

	--[[Drivetrain Initialize]]

	local Drive = {}

	--Power Front Wheels
	if _Tune.Config == "FWD" or _Tune.Config == "AWD" then
		for _, v in pairs(car.Wheels:GetChildren()) do
			if v.Name == "FL" or v.Name == "FR" or v.Name == "F" then
				table.insert(Drive, v)
			end
		end
	end

	--Power Rear Wheels
	if _Tune.Config == "RWD" or _Tune.Config == "AWD" then
		for _, v in pairs(car.Wheels:GetChildren()) do
			if v.Name == "RL" or v.Name == "RR" or v.Name == "R" then
				table.insert(Drive, v)
			end
		end
	end

	--Determine Wheel Size
	local wDia = 0
	for _, v in pairs(Drive) do
		if v.Size.x > wDia then
			wDia = v.Size.x
		end
	end

	--Pre-Toggled PBrake
	for _, v in pairs(car.Wheels:GetChildren()) do
		if v["#AV"]:IsA("BodyAngularVelocity") then
			if math.abs(v["#AV"].maxTorque.Magnitude - PBrakeForce) < 1 then
				_PBrake = true
			end
		else
			if math.abs(v["#AV"].MotorMaxTorque - PBrakeForce) < 1 then
				_PBrake = true
			end
		end
	end

	--[[Steering]]

	local function Steering()
		--Mouse Steer
		if _MSteer then
			local msWidth = math.max(1, mouse.ViewSizeX * _Tune.Peripherals.MSteerWidth / 200)
			local mdZone = _Tune.Peripherals.MSteerDZone / 100
			local mST = ((mouse.X - mouse.ViewSizeX / 2) / msWidth)
			if math.abs(mST) <= mdZone then
				_GSteerT = 0
			else
				_GSteerT = (math.max(math.min((math.abs(mST) - mdZone), (1 - mdZone)), 0) / (1 - mdZone))
						^ _Tune.MSteerExp
					* (mST / math.abs(mST))
			end
		end

		--Interpolate Steering
		if _GSteerC < _GSteerT then
			if _GSteerC < 0 then
				_GSteerC = math.min(_GSteerT, _GSteerC + _Tune.ReturnSpeed)
			else
				_GSteerC = math.min(_GSteerT, _GSteerC + _Tune.SteerSpeed)
			end
		else
			if _GSteerC > 0 then
				_GSteerC = math.max(_GSteerT, _GSteerC - _Tune.ReturnSpeed)
			else
				_GSteerC = math.max(_GSteerT, _GSteerC - _Tune.SteerSpeed)
			end
		end

		--Steer Decay Multiplier
		local sDecay = (1 - math.min(car.DriveSeat.Velocity.Magnitude / _Tune.SteerDecay, 1 - (_Tune.MinSteer / 100)))

		--Apply Steering
		for _, v in pairs(car.Wheels:GetChildren()) do
			if v.Name == "F" then
				v.Arm.Steer.CFrame = car.Wheels.F.Base.CFrame
					* CFrame.Angles(0, -math.rad(_GSteerC * _Tune.SteerInner * sDecay), 0)
			elseif v.Name == "FL" then
				if _GSteerC >= 0 then
					v.Arm.Steer.CFrame = car.Wheels.FL.Base.CFrame
						* CFrame.Angles(0, -math.rad(_GSteerC * _Tune.SteerOuter * sDecay), 0)
				else
					v.Arm.Steer.CFrame = car.Wheels.FL.Base.CFrame
						* CFrame.Angles(0, -math.rad(_GSteerC * _Tune.SteerInner * sDecay), 0)
				end
			elseif v.Name == "FR" then
				if _GSteerC >= 0 then
					v.Arm.Steer.CFrame = car.Wheels.FR.Base.CFrame
						* CFrame.Angles(0, -math.rad(_GSteerC * _Tune.SteerInner * sDecay), 0)
				else
					v.Arm.Steer.CFrame = car.Wheels.FR.Base.CFrame
						* CFrame.Angles(0, -math.rad(_GSteerC * _Tune.SteerOuter * sDecay), 0)
				end
			end
		end
	end

	--[[Engine]]

	local fFD = _Tune.FinalDrive * _Tune.FDMult
	local fFDr = fFD * 30 / math.pi
	local cGrav = workspace.Gravity * _Tune.InclineComp / 32.2
	local wDRatio = wDia * math.pi / 60
	local cfWRot = CFrame.Angles(math.pi / 2, -math.pi / 2, 0)
	local cfYRot = CFrame.Angles(0, math.pi, 0)
	local rtTwo = (2 ^ 0.5) / 2

	--Horsepower Curve
	local fgc_h = _Tune.Horsepower / 100
	local fgc_n = _Tune.PeakRPM / 1000
	local fgc_a = _Tune.PeakSharpness
	local fgc_c = _Tune.CurveMult

	local function FGC(x)
		x = x / 1000
		return (((-(x - fgc_n) ^ 2) * math.min(fgc_h / (fgc_n ^ 2), fgc_c ^ (fgc_n / fgc_h))) + fgc_h)
			* (x - ((x ^ fgc_a) / ((fgc_a * fgc_n) ^ (fgc_a - 1))))
	end
	local PeakFGC = FGC(_Tune.PeakRPM)

	--Plot Current Horsepower
	local function GetCurve(x, gear)
		local hp = math.max((FGC(x) * _Tune.Horsepower) / PeakFGC, 0)
		return hp, hp * (_Tune.EqPoint / x) * _Tune.Ratios[gear + 2] * fFD * hpScaling
	end

	--Output Cache
	local CacheTorque = true
	local HPCache = {}
	local HPInc = 100

	if CacheTorque then
		for gear in pairs(_Tune.Ratios) do
			local hpPlot = {}
			for rpm = math.floor(_Tune.IdleRPM / HPInc), math.ceil((_Tune.Redline + 100) / HPInc) do
				local tqPlot = {}
				tqPlot.Horsepower, tqPlot.Torque = GetCurve(rpm * HPInc, gear - 2)
				local hp1, tq1 = GetCurve((rpm + 1) * HPInc, gear - 2)
				tqPlot.HpSlope = (hp1 - tqPlot.Horsepower) / (HPInc / 1000)
				tqPlot.TqSlope = (tq1 - tqPlot.Torque) / (HPInc / 1000)
				hpPlot[rpm] = tqPlot
			end
			table.insert(HPCache, hpPlot)
		end
	end

	--Powertrain

	--Update RPM
	local function RPM()
		--Neutral Gear
		if _CGear == 0 then
			_ClutchOn = false
		end

		--Car Is Off
		local revMin = _Tune.IdleRPM
		if not _IsOn then
			revMin = 0
			_CGear = 0
			_ClutchOn = false
			_GThrot = _Tune.IdleThrottle / 100
		end

		--Determine RPM
		local maxSpin = 0
		for _, v in pairs(Drive) do
			if v.RotVelocity.Magnitude > maxSpin then
				maxSpin = v.RotVelocity.Magnitude
			end
		end
		if _ClutchOn then
			local aRPM = math.max(math.min(maxSpin * _Tune.Ratios[_CGear + 2] * fFDr, _Tune.Redline + 100), revMin)
			local clutchP = math.min(math.abs(aRPM - _RPM) / _Tune.ClutchTol, 0.9)
			_RPM = _RPM * clutchP + aRPM * (1 - clutchP)
		else
			if _GThrot - (_Tune.IdleThrottle / 100) > 0 then
				if _RPM > _Tune.Redline then
					_RPM = _RPM - _Tune.RevBounce * 2
				else
					_RPM = math.min(_RPM + _Tune.RevAccel * _GThrot, _Tune.Redline + 100)
				end
			else
				_RPM = math.max(_RPM - _Tune.RevDecay, revMin)
			end
		end

		--Rev Limiter
		_spLimit = (_Tune.Redline + 100) / (fFDr * _Tune.Ratios[_CGear + 2])
		if _RPM > _Tune.Redline then
			if _CGear < #_Tune.Ratios - 2 then
				_RPM = _RPM - _Tune.RevBounce
			else
				_RPM = _RPM - _Tune.RevBounce * 0.5
			end
		end
	end

	--Apply Power
	local function Engine()
		--Get Torque
		local maxSpin = 0
		for _, v in pairs(Drive) do
			if v.RotVelocity.Magnitude > maxSpin then
				maxSpin = v.RotVelocity.Magnitude
			end
		end
		if _ClutchOn then
			if CacheTorque then
				local cTq =
					HPCache[_CGear + 2][math.floor(math.min(_Tune.Redline, math.max(_Tune.IdleRPM, _RPM)) / HPInc)]
				_HP = cTq.Horsepower + (cTq.HpSlope * (_RPM - math.floor(_RPM / HPInc)) / 1000)
				_OutTorque = cTq.Torque + (cTq.TqSlope * (_RPM - math.floor(_RPM / HPInc)) / 1000)
			else
				_HP, _OutTorque = GetCurve(_RPM, _CGear)
			end
			local iComp = car.DriveSeat.CFrame.lookVector.y * cGrav
			if _CGear == -1 then
				iComp = -iComp
			end
			_OutTorque = _OutTorque * math.max(1, (1 + iComp))
		else
			_HP, _OutTorque = 0, 0
		end

		--Automatic Transmission
		if _TMode == "Auto" and _IsOn then
			_ClutchOn = true
			if _CGear == 0 then
				_CGear = 1
			end
			if _CGear >= 1 then
				if _CGear == 1 and _GBrake > 0 and car.DriveSeat.Velocity.Magnitude < 20 then
					_CGear = -1
				else
					if _Tune.AutoShiftMode == "RPM" then
						if _RPM > (_Tune.PeakRPM + _Tune.AutoUpThresh) then
							_CGear = math.min(_CGear + 1, #_Tune.Ratios - 2)
						elseif
							math.max(
								math.min(maxSpin * _Tune.Ratios[_CGear + 1] * fFDr, _Tune.Redline + 100),
								_Tune.IdleRPM
							) < (_Tune.PeakRPM - _Tune.AutoDownThresh)
						then
							_CGear = math.max(_CGear - 1, 1)
						end
					else
						if
							car.DriveSeat.Velocity.Magnitude
							> math.ceil(wDRatio * (_Tune.PeakRPM + _Tune.AutoUpThresh) / _Tune.Ratios[_CGear + 2] / fFD)
						then
							_CGear = math.min(_CGear + 1, #_Tune.Ratios - 2)
						elseif
							car.DriveSeat.Velocity.Magnitude
							< math.ceil(
								wDRatio * (_Tune.PeakRPM - _Tune.AutoDownThresh) / _Tune.Ratios[_CGear + 1] / fFD
							)
						then
							_CGear = math.max(_CGear - 1, 1)
						end
					end
				end
			else
				if _GThrot - (_Tune.IdleThrottle / 100) > 0 and car.DriveSeat.Velocity.Magnitude < 20 then
					_CGear = 1
				end
			end
		end

		--Average Rotational Speed Calculation
		local fwspeed = 0
		local fwcount = 0
		local rwspeed = 0
		local rwcount = 0

		for _, v in pairs(car.Wheels:GetChildren()) do
			if v.Name == "FL" or v.Name == "FR" or v.Name == "F" then
				fwspeed = fwspeed + v.RotVelocity.Magnitude
				fwcount = fwcount + 1
			elseif v.Name == "RL" or v.Name == "RR" or v.Name == "R" then
				rwspeed = rwspeed + v.RotVelocity.Magnitude
				rwcount = rwcount + 1
			end
		end
		fwspeed = fwspeed / fwcount
		rwspeed = rwspeed / rwcount
		local cwspeed = (fwspeed + rwspeed) / 2

		--Update Wheels
		for _, v in pairs(car.Wheels:GetChildren()) do
			--Reference Wheel Orientation
			local Ref = (CFrame.new(v.Position - (v.Arm.CFrame * cfWRot).lookVector, v.Position) * cfYRot).lookVector
			local aRef = 1
			local diffMult = 1
			if v.Name == "FL" or v.Name == "RL" then
				aRef = -1
			end

			--AWD Torque Scaling
			if _Tune.Config == "AWD" then
				_OutTorque = _OutTorque * rtTwo
			end

			--Differential/Torque-Vectoring
			if v.Name == "FL" or v.Name == "FR" then
				diffMult = math.max(
					0,
					math.min(
						1,
						1
							+ (
								(
									((v.RotVelocity.Magnitude - fwspeed) / fwspeed)
									/ (math.max(_Tune.FDiffSlipThres, 1) / 100)
								) * ((_Tune.FDiffLockThres - 50) / 50)
							)
					)
				)
				if _Tune.Config == "AWD" then
					diffMult = math.max(
						0,
						math.min(
							1,
							diffMult
								* (
									1
									+ (
										(((fwspeed - cwspeed) / cwspeed) / (math.max(_Tune.CDiffSlipThres, 1) / 100))
										* ((_Tune.CDiffLockThres - 50) / 50)
									)
								)
						)
					)
				end
			elseif v.Name == "RL" or v.Name == "RR" then
				diffMult = math.max(
					0,
					math.min(
						1,
						1
							+ (
								(
									((v.RotVelocity.Magnitude - rwspeed) / rwspeed)
									/ (math.max(_Tune.RDiffSlipThres, 1) / 100)
								) * ((_Tune.RDiffLockThres - 50) / 50)
							)
					)
				)
				if _Tune.Config == "AWD" then
					diffMult = math.max(
						0,
						math.min(
							1,
							diffMult
								* (
									1
									+ (
										(((rwspeed - cwspeed) / cwspeed) / (math.max(_Tune.CDiffSlipThres, 1) / 100))
										* ((_Tune.CDiffLockThres - 50) / 50)
									)
								)
						)
					)
				end
			end

			_TCSActive = false
			_ABSActive = false
			--Output
			if
				_PBrake
				and (
					(
						_Tune.Config ~= "FWD"
						and (
							((v.Name == "FL" or v.Name == "FR") and car.DriveSeat.Velocity.Magnitude < 20)
							or ((v.Name == "RR" or v.Name == "RL") and car.DriveSeat.Velocity.Magnitude >= 20)
						)
					) or (_Tune.Config == "FWD" and (v.Name == "RR" or v.Name == "RL"))
				)
			then
				--PBrake
				v["#AV"].maxTorque = Vector3.new(math.abs(Ref.x), math.abs(Ref.y), math.abs(Ref.z)) * PBrakeForce
				print(Vector3.new(math.abs(Ref.x), math.abs(Ref.y), math.abs(Ref.z)) * PBrakeForce)
				v["#AV"].angularvelocity = Vector3.new()
			else
				--Apply Power
				if
					((_TMode == "Manual" or _TMode == "Semi") and _GBrake == 0)
					or (
						_TMode == "Auto"
						and (
							(_CGear > -1 and _GBrake == 0)
							or (_CGear == -1 and _GThrot - (_Tune.IdleThrottle / 100) == 0)
						)
					)
				then
					local driven = false
					for _, a in pairs(Drive) do
						if a == v then
							driven = true
						end
					end
					if driven then
						local on = 1
						local isOn = gui:FindFirstChild("IsOn")
						if not isOn or not isOn.Value then
							on = 0
						end
						local throt = _GThrot
						if _TMode == "Auto" and _CGear == -1 then
							throt = _GBrake
						end

						--Apply TCS
						local tqTCS = 1
						if _TCS then
							tqTCS = 1
								- (
									math.min(
										math.max(
											0,
											math.abs(v.RotVelocity.Magnitude * (v.Size.x / 2) - v.Velocity.Magnitude)
												- _Tune.TCSThreshold
										) / _Tune.TCSGradient,
										1
									) * (1 - (_Tune.TCSLimit / 100))
								)
						end
						if tqTCS < 1 then
							_TCSActive = true
						end

						--Update Forces
						local dir = 1
						if _CGear == -1 then
							dir = -1
						end
						v["#AV"].maxTorque = Vector3.new(math.abs(Ref.x), math.abs(Ref.y), math.abs(Ref.z))
							* _OutTorque
							* (1 + (v.RotVelocity.Magnitude / 60) ^ 1.15)
							* throt
							* tqTCS
							* diffMult
							* on
						v["#AV"].angularvelocity = Ref * aRef * _spLimit * dir
					else
						v["#AV"].maxTorque = Vector3.new()
						v["#AV"].angularvelocity = Vector3.new()
					end

				--Brakes
				else
					local brake = _GBrake
					if _TMode == "Auto" and _CGear == -1 then
						brake = _GThrot
					end

					--Apply ABS
					local tqABS = 1
					if
						_ABS
						and math.abs(v.RotVelocity.Magnitude * (v.Size.x / 2) - v.Velocity.Magnitude)
								- _Tune.ABSThreshold
							> 0
					then
						tqABS = 0
					end
					if tqABS < 1 then
						_ABSActive = true
					end

					--Update Forces
					if v.Name == "FL" or v.Name == "FR" or v.Name == "F" then
						v["#AV"].maxTorque = Vector3.new(math.abs(Ref.x), math.abs(Ref.y), math.abs(Ref.z))
							* FBrakeForce
							* brake
							* tqABS
					else
						v["#AV"].maxTorque = Vector3.new(math.abs(Ref.x), math.abs(Ref.y), math.abs(Ref.z))
							* RBrakeForce
							* brake
							* tqABS
					end
					v["#AV"].angularvelocity = Vector3.new()
				end
			end
		end
	end

	--[[Flip]]

	local function Flip()
		--Detect Orientation
		if (car.DriveSeat.CFrame * CFrame.Angles(math.pi / 2, 0, 0)).lookVector.y > 0.1 or FlipDB then
			FlipWait = tick()

		--Apply Flip
		else
			if tick() - FlipWait >= 3 then
				FlipDB = true
				local gyro = car.DriveSeat.Flip
				gyro.maxTorque = Vector3.new(10000, 0, 10000)
				gyro.P = 3000
				gyro.D = 500
				task.wait(1)
				gyro.maxTorque = Vector3.new(0, 0, 0)
				gyro.P = 0
				gyro.D = 0
				FlipDB = false
			end
		end
	end

	local elapsed = 0

	local function Runtime(dt)
		--Steering
		Steering()

		--RPM
		RPM()

		--Update External Values
		if not gui or not gui:FindFirstChild("IsOn") then
			return
		end
		_IsOn = gui.IsOn.Value
		_InControls = gui.ControlsOpen.Value
		gui.Values.Gear.Value = _CGear
		gui.Values.RPM.Value = _RPM
		gui.Values.Horsepower.Value = _HP
		gui.Values.Torque.Value = _HP * _Tune.EqPoint / _RPM
		gui.Values.TransmissionMode.Value = _TMode
		gui.Values.Throttle.Value = _GThrot
		gui.Values.Brake.Value = _GBrake
		gui.Values.SteerC.Value = _GSteerC
			* (1 - math.min(car.DriveSeat.Velocity.Magnitude / _Tune.SteerDecay, 1 - (_Tune.MinSteer / 100)))
		gui.Values.SteerT.Value = _GSteerT
		gui.Values.PBrake.Value = _PBrake
		gui.Values.TCS.Value = _TCS
		gui.Values.TCSActive.Value = _TCSActive
		gui.Values.ABS.Value = _ABS
		gui.Values.ABSActive.Value = _ABSActive
		gui.Values.MouseSteerOn.Value = _MSteer
		gui.Values.Velocity.Value = car.DriveSeat.Velocity

		elapsed += dt

		if elapsed >= 0.0667 then
			elapsed = 0

			-- Power
			Engine()

			-- Flip
			if _Tune.AutoFlip then
				Flip()
			end
		end
	end

	--[[Shutdown]]

	local function clearConnections()
		for _, connection: RBXScriptConnection in connections do
			connection:Disconnect()
		end
	end
	local function removeGui()
		_PBrake = true
		task.wait()
		clearConnections()
		Engine()
	end

	--[[Run]]
	_PBrake = false
	connections[#connections + 1] = car.DriveSeat:GetPropertyChangedSignal("Occupant"):Connect(removeGui)
	connections[#connections + 1] = UserInputService.InputBegan:connect(DealWithInput)
	connections[#connections + 1] = UserInputService.InputChanged:connect(DealWithInput)
	connections[#connections + 1] = UserInputService.InputEnded:connect(DealWithInput)
	connections[#connections + 1] = Left.InputBegan:Connect(LeftTurn)
	connections[#connections + 1] = Left.InputEnded:Connect(LeftTurn)
	connections[#connections + 1] = Right.InputBegan:Connect(RightTurn)
	connections[#connections + 1] = Right.InputEnded:Connect(RightTurn)
	connections[#connections + 1] = Gas.InputBegan:Connect(TouchThrottle)
	connections[#connections + 1] = Gas.InputEnded:Connect(TouchThrottle)
	connections[#connections + 1] = Brake.InputBegan:Connect(TouchBrake)
	connections[#connections + 1] = Brake.InputEnded:Connect(TouchBrake)
	connections[#connections + 1] = Handbrake.InputBegan:Connect(TouchHandbrake)
	connections[#connections + 1] = Handbrake.InputEnded:Connect(TouchHandbrake)
	connections[#connections + 1] = RunService.Stepped:connect(Runtime)

	task.wait(15)
	removeGui()

	--[[END]]
end

return DriveModule
